# Generated by Django 5.0.6 on 2024-07-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
